chore: Rename list function name as list_xxx
open-v2x/dandelion pull request #10
Opened 2022-07-27 07:22 UTC by zhubx007

issue: #9

2022-07-27 08:00 UTC, wu-wenxiang requested changes
这里是不是我错了，list 比 list_objects 更好吧？:-(

2022-07-27 08:00 UTC, wu-wenxiang commented on dandelion/api/api_v1/endpoints/areas.py
> +def list_areas(
是不是我之前讲错了，list 比 list_objects 更好吧

2022-07-27 08:19 UTC, zhubx007 commented on dandelion/api/api_v1/endpoints/areas.py
> +def list_areas(
不过这里，list 确实是保留字段，这样会覆盖掉了 python 自身的 list。其余的 get delete update create 均可以。

2022-07-27 10:35 UTC, wu-wenxiang commented on dandelion/api/api_v1/endpoints/areas.py
> +def list_areas(
你看看其它项目怎么写的，是不是 get_one 和 get_all ?

2022-07-28 02:06 UTC, zhubx007 commented on dandelion/api/api_v1/endpoints/areas.py
> +def list_areas(
> 你看看其它项目怎么写的，是不是 get_one 和 get_all ?

Done, replace list with get_all.

2022-07-28 02:15 UTC, wu-wenxiang approved these changes

2022-07-28 02:16 UTC, wu-wenxiang approved these changes

2022-07-28 02:17 UTC, merged